version: '3.5'
services:
  backend:
    image: 'shop:latest'
    container_name: shop
    hostname: shop
    ports:
      - "8080:8081"
    build:
      context: .
    depends_on:
      - postgreSQL
    networks:
      - shop-network
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres-sql:5432/shop_db"

  postgreSQL:
    image: postgres
    container_name: postgres-sql
    hostname: postgres-sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=shop_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5454:5432
    networks:
      - shop-network

networks:
  shop-network:
    name: shop-network
    external: true